### ISSUE TITLE
Brushing files larger than 4G is not supported.

### ISSUE THREAD

**Issue by ssr123456789** [MisterZtr/recovery_device_realme_RMX3700#1]

**Comment by MisterZtr** [comment]
Can you expand on that?

**Comment by ssr123456789** [comment]
> Can you expand on that?

If the ROM is larger than 4G, it can't be swiped. It can be solved by modifying twrp. I have seen other twrp can solve this problem by modifying twrp. I don't know if you can do anything about it.
![Uploading Screenshot_2024-03-10-07-30-38-22_97550f1d11c73369bbee8f7d47965447.jpg…]()

**Comment by ssr123456789** [comment]
![Screenshot_2024-03-10-07-30-38-22_97550f1d11c73369bbee8f7d47965447](https://github.com/MisterZtr/recovery_device_realme_RMX3700/assets/22828676/a2048ad8-8a70-40b4-81cc-54c857d8181e)

**Comment by zeng-github01** [comment]
This issue seems to have been fixed in TWRP. Would you like to take a look?

https://gerrit.twrp.me/c/android_bootable_recovery/+/5689/6#message-818a383c31e6ffcd027e7f862351683b402efd72

@MisterZtr

**Comment by zeng-github01** [comment]
> > Can you expand on that?
> 
> If the ROM is larger than 4G, it can't be swiped. It can be solved by modifying twrp. I have seen other twrp can solve this problem by modifying twrp. I don't know if you can do anything about it.
> ![Uploading Screenshot_2024-03-10-07-30-38-22_97550f1d11c73369bbee8f7d47965447.jpg…]()
> 

The picture is broken

**Comment by MisterZtr** [comment]
> This issue seems to have been fixed in TWRP. Would you like to take a look?

This commit is already applied

**Comment by MisterZtr** [comment]
> If the ROM is larger than 4G, it can't be swiped

I can install full ota, which weighs more than 4GB, including via adb sideload

**Comment by zeng-github01** [comment]
> > If the ROM is larger than 4G, it can't be swiped
> 
> I can install full ota, which weighs more than 4GB, including via adb sideload

If so, this issue cannot be confirmed. It seems that the only option is to close it.

Now RMX3700 has official Android 14. Will you try to adapt it? If I remember correctly, TWRP is not supported yet. I don't know why.

**Comment by zeng-github01** [comment]
> > If the ROM is larger than 4G, it can't be swiped
> 
> I can install full ota, which weighs more than 4GB, including via adb sideload

Another possibility is that OPLUS made some changes to the payload. A developer I know also encountered an exception when flashing the payload. He used a self-made program to fix this

**Comment by MisterZtr** [comment]
> Now RMX3700 has official Android 14. Will you try to adapt it?

OrangeFox fully support android 14

**Comment by zeng-github01** [comment]
> > Now RMX3700 has official Android 14. Will you try to adapt it?
> 
> OrangeFox fully support android 14

Am I mistaken? I remember that it needs additional adaptation. It is not universal.

Just like the decryption from Android 11 to 12

**Comment by MisterZtr** [comment]
Can you check for this problem in new build?
https://drive.google.com/file/d/1_NP1sa8EMxVHBGm6Fw7CfiLyu4SWJcQg/view?usp=sharing

**Comment by walunt236** [comment]
The current version cannot flash the payload.bin file and will report an
error. The payload.bin is about 7G.

Andrew ***@***.***> 于 2024年4月10日周三 02:40写道：

**Comment by MisterZtr** [comment]
You can't flash Payload.bin. You can only install paylaod ROMs, which have an installation archive
