### ISSUE TITLE
Realme neo 6se

### ISSUE THREAD

**Issue by helpmebro911** [MisterZtr/recovery_device_realme_RMX3700#8]
pls add support Realme neo 6se

**Comment by MisterZtr** [comment]
This tree is only for the realme gt neo 5 se. There is another repository for the realme gt neo 6 se, and I'm tired of doing it
https://github.com/MisterZtr/recovery_device_realme_pineapple

**Comment by helpmebro911** [comment]
please make it
i am ready to test
